# This file will be sent over jsonrpc to the server for the `initialize` request

root_path = "./coolstore"
analyzer_lsp_java_bundle_path = "./analysis/bundle.jar"
analyzer_lsp_lsp_path = "./analysis/jdtls/bin/jdtls"
analyzer_lsp_rpc_path = "./analysis/kai-analyzer-rpc"
analyzer_lsp_rules_path = "./analysis/rulesets/default/generated"
analyzer_lsp_dep_labels_path = "./analysis/maven.default.index"

demo_mode = true
cache_dir = "???"
enable_reflection = false

[log_config]
log_level = "INFO"
file_log_level = "DEBUG"
log_dir_path = "./logs"

[models]
provider = "ChatOpenAI"

[models.args]
model = "gpt-3.5-turbo"
