[postgresql]
host = "127.0.0.1"
database = "kai"
user = "kai"
password = "dog8code"

[models]
provider = "IBMGranite"
args = { model_id = "ibm/granite-13b-chat-v2" } # model_id is optional

# Here for later, we want to be able to configure which embeddings are used when
# we start to integrate them into the project
[embeddings]
todo = true
